export const DRIVER_AUDIT_ACTIONS = {
  DRIVER_MODE_OPENED: "DRIVER_MODE_OPENED",
  DRIVER_LANGUAGE_CHANGED: "DRIVER_LANGUAGE_CHANGED",
  DRIVER_VOICE_ACCEPTED: "DRIVER_VOICE_ACCEPTED",
  DRIVER_VOICE_REJECTED: "DRIVER_VOICE_REJECTED",
  DRIVER_VEHICLE_CONFIRMED: "DRIVER_VEHICLE_CONFIRMED",
  DRIVER_DOCUMENT_SCAN_REQUESTED: "DRIVER_DOCUMENT_SCAN_REQUESTED",
  DRIVER_WORKFLOW_ACTION: "DRIVER_WORKFLOW_ACTION",
  DRIVER_UNLOADING_STARTED: "DRIVER_UNLOADING_STARTED",
  DRIVER_UNLOADING_COMPLETED: "DRIVER_UNLOADING_COMPLETED",
  DRIVER_TRANSACTION_COMPLETED: "DRIVER_TRANSACTION_COMPLETED",
  DRIVER_EXCEPTION_ACKNOWLEDGED: "DRIVER_EXCEPTION_ACKNOWLEDGED",
  DRIVER_AUDIO_TOGGLED: "DRIVER_AUDIO_TOGGLED",
} as const;

export type DriverAuditAction = (typeof DRIVER_AUDIT_ACTIONS)[keyof typeof DRIVER_AUDIT_ACTIONS];

export function isDriverAuditAction(value: string): value is DriverAuditAction {
  return Object.values(DRIVER_AUDIT_ACTIONS).includes(value as DriverAuditAction);
}
