export const MASTER_DATA_SCOPES = {
  permission: "GLOBAL",
  organization: "GLOBAL_SLUG",
  role: "ORGANIZATION",
  department: "ORGANIZATION",
  user: "ORGANIZATION",
  material: "ORGANIZATION",
  workflow: "ORGANIZATION",
  vehicle: "ORGANIZATION",
  driver: "ORGANIZATION",
  supplier: "ORGANIZATION",
  site: "ORGANIZATION",
  weighbridge: "SITE",
  unloadingPoint: "SITE",
  camera: "SITE",
  gateway: "SITE",
  device: "GATEWAY",
  transaction: "SITE",
  document: "TRANSACTION",
  approval: "TRANSACTION",
  unloading: "TRANSACTION",
  notification: "ORGANIZATION_AND_RECIPIENT",
  auditLog: "ORGANIZATION",
  securityEvent: "SITE",
  weightAnomaly: "WEIGHBRIDGE",
  onboardingSession: "ORGANIZATION",
} as const;

export const UNIQUE_WITHIN = {
  organizationSlug: "GLOBAL",
  permissionCode: "GLOBAL",
  siteCode: "ORGANIZATION",
  departmentCode: "ORGANIZATION",
  roleCode: "ORGANIZATION",
  userEmail: "ORGANIZATION",
  vehicleRegistration: "ORGANIZATION",
  materialCode: "ORGANIZATION",
  supplierCode: "ORGANIZATION",
  workflowCode: "ORGANIZATION",
  driverLicense: "ORGANIZATION",
  weighbridgeCode: "SITE",
  unloadingPointCode: "SITE",
  gatewayCode: "ORGANIZATION",
  edgeDeviceCode: "GATEWAY",
  transactionReference: "ORGANIZATION",
} as const;
